### ISSUE TITLE
Not currently working with v1.2

### ISSUE THREAD

**Issue by terryupton** [adfdev/tailwindcss-bg-alpha#3]
This plugin seems to not function with Tailwind 1.2.
It might be something I am doing wrong, but I cannot stop the plugin generating the defaults only.

Here is what I have tried:

```
  variants: {
    alphaColors: ['responsive']
  },
```
I would expect only the responsive styles but I get all the hovers and focus styles too.

module.exports = {
```
alphaColors: ['red.500', 'gray.200', 'brand-grue.950']
```
I would expect the above colours only in those alpha settings.

However, it only ever generates white and black for bg, border and text (10-100) in responsive, hover, group-hover and focus

on another Project. I have the following:
```
      alphaValues: [
        0.25, 0.50, 0.80
      ]
```

However, it only still generates white and black for bg, border and text (10-100) in responsive, hover, group-hover and focus. Although it does also generate the 0.25 versions. I would expect it only to generate those 3 versions set - (0.25, 0.5 and 0.8).

**Comment by cenda** [comment]
Have you tried to put `alphaColors` / `alphaValues` into `theme` section of your `tailwind.config.js` file?

this worked for me:
```
module.exports = {
    ...
    theme: {
        extend: {
            colors: {
                primary: '#B673E5'
            }
        },
        alphaColors: ['primary'],
        alphaValues: [0.1, 0.4],
    },
    plugins: [
        require('tailwindcss-bg-alpha')(),
    ],
    ...
};
```

**Comment by richardthombs** [comment]
@cenda That works for me too, thx!

**Comment by adfdev** [comment]
Solved!
